# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src\designer\aboutdialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AboutDialog(object):
    def setupUi(self, AboutDialog):
        AboutDialog.setObjectName("AboutDialog")
        AboutDialog.resize(400, 200)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AboutDialog.sizePolicy().hasHeightForWidth())
        AboutDialog.setSizePolicy(sizePolicy)
        AboutDialog.setMinimumSize(QtCore.QSize(400, 200))
        AboutDialog.setMaximumSize(QtCore.QSize(400, 200))
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(AboutDialog)
        self.verticalLayout_3.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(AboutDialog)
        self.label.setMinimumSize(QtCore.QSize(50, 50))
        self.label.setMaximumSize(QtCore.QSize(50, 50))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/icons/course_30px.png"))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 8, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.labelName = QtWidgets.QLabel(AboutDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelName.setFont(font)
        self.labelName.setObjectName("labelName")
        self.verticalLayout.addWidget(self.labelName)
        self.labelAuthor = QtWidgets.QLabel(AboutDialog)
        self.labelAuthor.setObjectName("labelAuthor")
        self.verticalLayout.addWidget(self.labelAuthor)
        spacerItem2 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem2)
        self.labelIconsCredits = QtWidgets.QLabel(AboutDialog)
        self.labelIconsCredits.setObjectName("labelIconsCredits")
        self.verticalLayout.addWidget(self.labelIconsCredits)
        self.labelRuporCredits = QtWidgets.QLabel(AboutDialog)
        self.labelRuporCredits.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelRuporCredits.setObjectName("labelRuporCredits")
        self.verticalLayout.addWidget(self.labelRuporCredits)
        self.labelNewVersion = QtWidgets.QLabel(AboutDialog)
        self.labelNewVersion.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelNewVersion.setObjectName("labelNewVersion")
        self.verticalLayout.addWidget(self.labelNewVersion)
        self.verticalLayout.setStretch(6, 1)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(AboutDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_3.addWidget(self.buttonBox)

        self.retranslateUi(AboutDialog)
        self.buttonBox.accepted.connect(AboutDialog.accept)
        self.buttonBox.rejected.connect(AboutDialog.reject)
        self.labelIconsCredits.linkActivated['QString'].connect(AboutDialog.openLink)
        self.labelRuporCredits.linkActivated['QString'].connect(AboutDialog.openLink)
        self.labelNewVersion.linkActivated['QString'].connect(AboutDialog.openLink)
        QtCore.QMetaObject.connectSlotsByName(AboutDialog)

    def retranslateUi(self, AboutDialog):
        _translate = QtCore.QCoreApplication.translate
        AboutDialog.setWindowTitle(_translate("AboutDialog", "About Libro2"))
        self.labelName.setText(_translate("AboutDialog", "Libro2 v1.0"))
        self.labelAuthor.setText(_translate("AboutDialog", "Written by dnk_dz"))
        self.labelIconsCredits.setText(_translate("AboutDialog", "<html><head/><body><p>Icons by <a href=\"https://icons8.com/\"><span style=\" text-decoration: underline; color:#0000ff;\">icons8.com</span></a></p></body></html>"))
        self.labelRuporCredits.setText(_translate("AboutDialog", "<html><head/><body><p>Special sanks to <a href=\"https://github.com/rupor-github\"><span style=\" text-decoration: underline; color:#0000ff;\">rupor</span></a> for <a href=\"https://github.com/rupor-github/fb2converter\"><span style=\" text-decoration: underline; color:#0000ff;\">fb2converter</span></a> and <a href=\"https://github.com/rupor-github/fb2mobi\"><span style=\" text-decoration: underline; color:#0000ff;\">fb2mobi</span></a></p></body></html>"))
        self.labelNewVersion.setText(_translate("AboutDialog", "<html><head/><body><p>Check new version <a href=\"https://github.com/dnkorpushov/libro2/releases\"><span style=\" text-decoration: underline; color:#0000ff;\">here</span></a></p></body></html>"))
from . import resources_rc
