# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src\designer\convertdialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConvertDialog(object):
    def setupUi(self, ConvertDialog):
        ConvertDialog.setObjectName("ConvertDialog")
        ConvertDialog.resize(493, 290)
        self.verticalLayout = QtWidgets.QVBoxLayout(ConvertDialog)
        self.verticalLayout.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(ConvertDialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.comboFormat = QtWidgets.QComboBox(ConvertDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboFormat.sizePolicy().hasHeightForWidth())
        self.comboFormat.setSizePolicy(sizePolicy)
        self.comboFormat.setObjectName("comboFormat")
        self.comboFormat.addItem("")
        self.comboFormat.addItem("")
        self.comboFormat.addItem("")
        self.comboFormat.addItem("")
        self.verticalLayout.addWidget(self.comboFormat)
        self.radioConvertInSourceFolder = QtWidgets.QRadioButton(ConvertDialog)
        self.radioConvertInSourceFolder.setObjectName("radioConvertInSourceFolder")
        self.verticalLayout.addWidget(self.radioConvertInSourceFolder)
        self.radioConvertTo = QtWidgets.QRadioButton(ConvertDialog)
        self.radioConvertTo.setObjectName("radioConvertTo")
        self.verticalLayout.addWidget(self.radioConvertTo)
        self.textOutputDir = ButtonLineEdit(ConvertDialog)
        self.textOutputDir.setObjectName("textOutputDir")
        self.verticalLayout.addWidget(self.textOutputDir)
        self.checkOverwrite = QtWidgets.QCheckBox(ConvertDialog)
        self.checkOverwrite.setObjectName("checkOverwrite")
        self.verticalLayout.addWidget(self.checkOverwrite)
        self.checkStk = QtWidgets.QCheckBox(ConvertDialog)
        self.checkStk.setObjectName("checkStk")
        self.verticalLayout.addWidget(self.checkStk)
        self.checkDebug = QtWidgets.QCheckBox(ConvertDialog)
        self.checkDebug.setObjectName("checkDebug")
        self.verticalLayout.addWidget(self.checkDebug)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.buttonBox = QtWidgets.QDialogButtonBox(ConvertDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(ConvertDialog)
        self.buttonBox.accepted.connect(ConvertDialog.accept)
        self.buttonBox.rejected.connect(ConvertDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ConvertDialog)

    def retranslateUi(self, ConvertDialog):
        _translate = QtCore.QCoreApplication.translate
        ConvertDialog.setWindowTitle(_translate("ConvertDialog", "Convert"))
        self.label.setText(_translate("ConvertDialog", "Output format"))
        self.comboFormat.setItemText(0, _translate("ConvertDialog", "epub"))
        self.comboFormat.setItemText(1, _translate("ConvertDialog", "kepub"))
        self.comboFormat.setItemText(2, _translate("ConvertDialog", "mobi"))
        self.comboFormat.setItemText(3, _translate("ConvertDialog", "azw3"))
        self.radioConvertInSourceFolder.setText(_translate("ConvertDialog", "Convert in source folder"))
        self.radioConvertTo.setText(_translate("ConvertDialog", "Convert to:"))
        self.checkOverwrite.setText(_translate("ConvertDialog", "Overwrite existing files"))
        self.checkStk.setText(_translate("ConvertDialog", "Send to Kindle"))
        self.checkDebug.setToolTip(_translate("ConvertDialog", "Prepare archive with details for debugging"))
        self.checkDebug.setText(_translate("ConvertDialog", "Debug"))
from .customcontrols import ButtonLineEdit
