# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src\designer\renamedialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RenameDialog(object):
    def setupUi(self, RenameDialog):
        RenameDialog.setObjectName("RenameDialog")
        RenameDialog.resize(515, 290)
        RenameDialog.setMinimumSize(QtCore.QSize(500, 220))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(RenameDialog)
        self.verticalLayout_2.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(RenameDialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.textAuthorFormat = QtWidgets.QComboBox(RenameDialog)
        self.textAuthorFormat.setEditable(True)
        self.textAuthorFormat.setObjectName("textAuthorFormat")
        self.verticalLayout.addWidget(self.textAuthorFormat)
        self.label_3 = QtWidgets.QLabel(RenameDialog)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.textFilenameFormat = QtWidgets.QComboBox(RenameDialog)
        self.textFilenameFormat.setEditable(True)
        self.textFilenameFormat.setObjectName("textFilenameFormat")
        self.verticalLayout.addWidget(self.textFilenameFormat)
        spacerItem = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.labelSample = QtWidgets.QLabel(RenameDialog)
        self.labelSample.setObjectName("labelSample")
        self.verticalLayout.addWidget(self.labelSample)
        spacerItem1 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.checkDeleteSource = QtWidgets.QCheckBox(RenameDialog)
        self.checkDeleteSource.setObjectName("checkDeleteSource")
        self.verticalLayout.addWidget(self.checkDeleteSource)
        self.checkBackup = QtWidgets.QCheckBox(RenameDialog)
        self.checkBackup.setObjectName("checkBackup")
        self.verticalLayout.addWidget(self.checkBackup)
        self.checkOverwrite = QtWidgets.QCheckBox(RenameDialog)
        self.checkOverwrite.setObjectName("checkOverwrite")
        self.verticalLayout.addWidget(self.checkOverwrite)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.buttonPreview = QtWidgets.QPushButton(RenameDialog)
        self.buttonPreview.setObjectName("buttonPreview")
        self.horizontalLayout.addWidget(self.buttonPreview)
        self.buttonBox = QtWidgets.QDialogButtonBox(RenameDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(RenameDialog)
        self.buttonBox.accepted.connect(RenameDialog.accept)
        self.buttonBox.rejected.connect(RenameDialog.reject)
        self.buttonPreview.clicked.connect(RenameDialog.onPreviewClick)
        QtCore.QMetaObject.connectSlotsByName(RenameDialog)

    def retranslateUi(self, RenameDialog):
        _translate = QtCore.QCoreApplication.translate
        RenameDialog.setWindowTitle(_translate("RenameDialog", "Rename"))
        self.label.setText(_translate("RenameDialog", "Author format:"))
        self.label_3.setText(_translate("RenameDialog", "Filename format:"))
        self.labelSample.setText(_translate("RenameDialog", "TextLabel"))
        self.checkDeleteSource.setText(_translate("RenameDialog", "Delete source files"))
        self.checkBackup.setText(_translate("RenameDialog", "Backup files before rename"))
        self.checkOverwrite.setText(_translate("RenameDialog", "Overwrite exsiting files"))
        self.buttonPreview.setText(_translate("RenameDialog", "Preview"))
from . import resources_rc
